name: Deploy to server

on: push

jobs:
  first_job:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Hello", "CodigoFacilito", "Bootcamp Github Action"]
    
    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"
